application/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blogs/', include('posts.urls', namespace = 'blogs')),
    url(r'^',include('core.urls',namespace='core')),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout
from .views import *

urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
    url(r'^logout/$', logout, name = "logout"),
    url(r'^login/$', login, {'template_name' : "core/login.html"}, name = "login"),
]

posts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^$', BlogList.as_view(), name="blogs_list"),
    url(r'^(?P<pk>\d+)$', BlogView.as_view(), name="one_blog"),
    url(r'^(?P<pk>\d+)/edit$', UpdateBlog.as_view(), name="edit_blog"),
    url(r'^add$', login_required(CreateBlog.as_view()), name="new_blog"),

    url(r'^post/(?P<pk>\d+)/edit$', login_required(UpdatePost.as_view()), name="edit_post"),
    url(r'^(?P<pk>\d+)/add$', login_required(CreatePost.as_view()), name="add_post"),

    url(r'^post/(?P<pk>\d+)$', PostDetail.as_view(), name="one_post"),
    url(r'^post/(?P<pk>\d+)/add_comment$', PostDetail.as_view(), name="detail_post"),
    url(r'^categories/$', CategoryList.as_view(), name="category_list"),
    url(r'^category/(?P<pk>\d+)$', CategoryView.as_view(), name="one_category"),
    url(r'^like/(?P<pk>\d+)$', PostLikeAjaxView.as_view(), name="post_ajax_like"),
    url(r'^likes/(?P<pk>\d+)$', BlogLikeView.as_view(), name="blog_likes")
]

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django demo blog app</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "/css/blog.css" %}">

    <meta name="csrf" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container-fluid">
    <header>
        {% block header %}
            <div class="row page-header text-center">
                <div class="row">
                    {% if user.is_authenticated %}
                        <div class="col-lg-6 col-md-6 col-xs-12"><h3>You are logged as <i>{{ user }}</i></h3></div><div class="col-lg-6 col-md-6 col-xs-12"><a
                                href="{% url "core:logout" %}">Logout</a></div>
                    {% else %}
                        <div class="col-lg-6 col-md-6 col-xs-12">
                            <h3>You are <i>not</i> logged in.</h3>
                        </div>
                        <div class="col-lg-6 col-md-8 col-xs-12"><a href="{% url "core:login" %}">Login</a></div></div>
                    {% endif %}
            </div>
        {% endblock %}
    </header>
    <nav>{% block navbar %}
        <div class="row  text-center">
            <div class="col-xs-12 col-md-3 col-lg-2"><a href="{% url "core:index" %}">Main page</a></div>
            <div class="col-xs-12 col-md-3 col-lg-2"><a href={% url "blogs:blogs_list" %}>All blogs</a></div>
            <div class="col-xs-12 col-md-3 col-lg-2"><a href="/blogs/categories/">All categories</a><br></div>
            <div class="col-xs-12 col-md-3 col-lg-2"><a href="/admin/">Admin panel</a></div>
            {% if user.is_authenticated %}
                <div class="col-xs-12 col-md-1 col-lg-2"><a href="{% url "blogs:new_blog" %}">Create new blog</a>
                </div>{% endif %}
        </div>
    {% endblock %}</nav>
    <article>
        <div class="row">
            <div class="text-center">{% block title %}{% endblock %}
            </div>
        </div>
        <div class="panel-body">{% block content %} {% endblock %}</div>
    </article>
    <footer>
        {% block footer %}
            <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12" id="footer">
                <div class="row panel-footer"><span class="center-block">This demo app is powered by Django</span></div>
            </div>{% endblock %}
    </footer>
</div>
<script src="{% static "/js/jquery-3.2.0.min.js" %}"></script>
<script src="{% static "/js/bootstrap.js" %}"></script>
<script src="{% static "js/base.js" %}"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% block title %}<h1>Welcome!</h1>{% endblock %}
{% block content %}
    <span class="panel-body">Welcome to the main page. Use navbar to navigate through blogs and categories.This site is still under construction. Search, Sorting, Registration and Likes will be implemented here soon</span>
{% endblock %}

posts/templates/blogs/addblog.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% block title %}<h1>Add new blog:</h1>{% endblock %}
{% block content %}
    <div class="row">
        <form method="POST" action="{% url "blogs:new_blog" %}">
            {% csrf_token %}
            <div class="col-md-6 col-xs-12">Category:</div>
            <div class="col-md-6 col-xs-12">{{ form.category }}</div>
            <div class="col-md-6 col-xs-12">Description:</div>
            <div class="col-md-6 col-xs-12"> {{ form.description | add_class:"text-area" }}</div>
            <div class="col-md-6 col-xs-12 col-md-offset-6"><input type="submit" class="btn" label="Apply!"></div>
        </form>
    </div>
{% endblock %}

posts/templates/blogs/all.html
{% extends "core/base.html" %}
{% block title %}<h1>Blog list</h1>{% endblock %}
{% block content %}
    {% if object_list.count %}
        <table class="table">
            <tbody>
            <tr><th>Name</th><th>Action</th><th>Date</th><th>Owner</th><th>Post count</th></tr>
            {% for blog in object_list %}
                <tr>
                    <td><a href='{% url "blogs:one_blog" pk=blog.id %}'>{{ blog.title }}</a>
                    </td>
                    <td>{% if blog.owner == user %}
                        <a href='{% url "blogs:edit_blog" pk=blog.id %}'>
                            Edit</a>
                    {% endif %}
                    </td>
                    <td>
                        {{ blog.date }}
                    <td>{{ blog.owner }}</td>
                    <td>Posts: {{ blog.post_set.count }} </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <span>Sorry, there is no blogs yet</span>
    {% endif %}

{% endblock %}

posts/templates/blogs/categories.html
{% extends "core/base.html" %}
{% block title %}<h1>All categories:</h1>{% endblock %}
{% block content %}
    {% if object_list.count %}
        <table class ="table">
        <tbody>
            {% for category in object_list %}
                <tr>
                    <td><a href='{% url "blogs:one_category" pk=category.id %}'>{{ category.title }}</a></td>
                    <td><b>Blogs:</b>{{ category.blog_set.count }}</td>
                    <td>{{ category.date }}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    {% else %}
        <h1 align="center">There is no categories yet</h1>
    {% endif %}
{% endblock %}

posts/templates/blogs/category.html
{% extends "core/base.html" %}
{% block title %}<h1><i>{{ object.name }}'s</i> tagged blogs:</h1>{% endblock %}
{% block content %}
    {% if object.blog_set.count %}
        <table class="table">
        <tr><th>Name</th><th>Action</th><th>Blog count</th></tr>
            {% for blog in object.blog_set.all %}
                <tr>
                    <td><a href='{% url "blogs:one_blog" pk=blog.id %}'>{{ blog.title }}</a></td><td>
                        {% if blog.owner == user %}
                            <a href='{% url "blogs:edit_blog" pk=blog.id %}'>
                                Edit</a>
                        {% endif %}
                    </td>
                    <td>
                    {{ blog.date }}
                    <td>{{ blog.owner }}</td>
                    <td>Posts: {{ blog.post_set.count }} </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h1 class="panel-body">There is no blogs yet</h1>
    {% endif %}
{% endblock %}

posts/templates/blogs/editblog.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% block title %}<h1 class="text-center">Blog properties:</h1>{% endblock %}
{% block content %}
<div class="row">
                <form method="POST" action="{% url "blogs:edit_blog" pk=object.id %}" class="form-inline">
                    {% csrf_token %}
                    <div class="row"><div class="col-md-3 col-xs-12">Title:</div> <div class="col-md-3 col-xs-12">{{ form.title | add_class:"form-control" }}</div></div>
                    <div class="row"><div class="col-md-3 col-xs-12">Description:</div> <div class="col-md-3 col-xs-12"> {{ form.description | add_class:"form-control" }}</div></div>
                    <div class="row"><div class="col-md-3 col-xs-12">Category:</div> <div class="col-md-3 col-xs-12"> {{ form.category }}</div></div>
                     <div class="row"><div class="col-md-3 col-xs-12 col-md-offset-4"><input type="submit" class="btn" label="Apply!"></div></div>
                </form>
</div>
{% endblock %}

posts/templates/posts/addpost.html
{% extends "core/base.html" %}
{% block title %}<h1>New post:</h1>{% endblock %}
{% block content %}
    <table align="center">
    <tr><td>
        <form method='POST'>
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Add post">
        </form>
    </td></tr>
    </table>
{% endblock %}

posts/templates/posts/post.html
{% extends "core/base.html" %}

{% block title %}
    <h1>{{ post.title }}</h1>
    <br><p style="text-align: left; font-size: 8pt; color: darkgray">{{ object.date }}</p> {% endblock %}

{% block content %}
    <p style="text-align: justify; font-size: 14pt; color: black">
        {{ post.text }}
    </p>

    {% if post.comment_set.count %}
        <table class="table">
        <tbody>
        <tr>
            <th><h2>Comments:</h2></th>
        </tr>
        {% for comment in post.comment_set.all %}
            <tr>
                <td>
                    <table align="left" cellspacing="2">
                        <tr>
                            <td><i>{{ comment.author }}</i> said on {{ comment.date }}</td>
                        </tr>
                        <tr>
                            <td>{{ comment.text }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <h1 align="center">There is no comments yet</h1>
    {% endif %}
</tbody>
</table>
    {% if user.is_authenticated %}
        <form method='post'>
            {% csrf_token %}
            {{ form }}
            <input type='submit' class="btn" value="Leave comment!">
        </form>
        {% else %}
        <h3>Login to leave comments</h3>
    {% endif %}
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "core/base.html" %}

{% block title %}
    <br><h2><a href="{% url "blogs:blogs_list" %}">To all blogs</a></h2>
    <h1>{{ object.title }}</h1>
    <br><p style = "text-align: left; font-size: 8pt; color: darkgray">{{ object.date }}</p> {% endblock %}

{% block content %}
    <p style="text-align: justify; font-size: 14pt; color: black">
    {{ object.text }}
    </p>
    <hr size="2">

    <table align="left>" cellspacing = 5>
    {% if objects.comment_set.count %}
    <tr><th><h2>Comments:</h2></th></tr>
    {% for comment in objects.comment_set.all %}
        <tr><td>
        <table class="table">
            <tr><td><i>{{ comment.author }}</i> said on {{ comment.date }}</td></tr>
            <tr><td>{{ comment.text }}</td></tr>
        </table>
        </td>
        </tr>
    {% endfor %}
    {%  else %}
        <h1 align="center">There is no comments yet</h1>
    {% endif %}
    {% if user.is_authenticated %}
    <tr><td><form method = 'post'>
        {%  csrf_token %}
        {{ form }}
        <input type = 'submit' class="btn-block" value="Comment!">
        </form>
    </td></tr>
    {% endif  %}
    </table>

{% endblock %}

posts/templates/posts/posts.html
{% extends "core/base.html" %}

{% block title %}
    <div class="row">
        <div class="col-md-10 col-xs-12">
            <h1>{{ object.title }} by <i>{{ object.owner }}</i></h1></div>
        <div class="col-md-2 col-xs-12">
            <a href='{% url "blogs:edit_blog" pk=object.id %}'>Edit</a></div>
    </div>
{% endblock %}
{% block content %}
    {% if object.owner == user %}
        <div class="row">
            <a href='{% url "blogs:add_post" pk=object.id %}'>
                New post</a></div>
    {% endif %}
    <div class="col-md-12 col-lg-12 blog" data-url="{% url "blogs:blog_likes" pk=object.id %}"></div>
    {% if object.post_set.all.count %}
        {% for post in object.post_set.all %}
            <div class="row" >
                <div><a href="{% url "blogs:one_post" pk=post.id %}">{{ post.title }}</a></div>
                <div class="col-md-3 col-lg-2 col-xs-12">{{ post.date }}</div>
                <div class="col-md-3 col-lg-2 col-xs-12"><i>Comments: {{ post.comment_set.count }}</i></div>
                <div class="col-md-3 col-lg-2 col-xs-12"><i>
                    <span id="likes-{{ post.id }}" class="like" data-url="{% url "blogs:post_ajax_like" pk=post.id %}" data-postid="{{ post.id }}">Количество лайков поста</span>
                    <button class="btn ajaxlike" data-url="{% url "blogs:post_ajax_like" pk=post.id %}"
                            data-postid="{{ post.id }}">Лайкнуть
                    </button>
                </i>
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h1 align="center">There is no posts yet</h1>
    {% endif %}
{% endblock %}